import React from "react"
import images from "src/images"
import { OpenContactModalButton } from "components"

const iwsContent = {
  sections: [
    {
      menuItem: "title",
      title: "Trucks and Trailers",
      subtitle: "Looking for truck financing? We got you covered.",
      image: {
        src: images.equipment.truckIndustry,
        alt: "Trucks and Trailers",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Reefer vans",
        "Construction trucks",
        "Logging vehicles",
        "Heavy trucks",
        "Heavy trailers",
        "Aerial lifts",
        "Class 8 trucks",
        "Dry freight vans",
        "Vac trucks",
        "Water trucks",
        "Utility trailers",
        "More vehicle leasing",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Construction",
      title: "Construction Equipment",
      subtitle: "Construction equipment leasing made easy.",
      image: {
        src: images.equipment.constructionIndustry,
        alt: "Construction",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Bobcats",
        "Gravel trucks",
        "Compactors",
        "Cranes, hoists, and lifts",
        "Demolition equipment",
        "Dozers",
        "Excavators",
        "Generator sets",
        "Hydraulic equipment",
        "Mixers",
        "Skid steers",
        "Cargo trailers",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Forestry",
      title: "Forestry Equipment",
      subtitle: "We lease forestry equipment of all sorts.",
      image: {
        src: images.equipment.forestryIndustry,
        alt: "Forestry",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Logging trucks",
        "Logging trailers",
        "Grapple skidders",
        "Feller bunchers",
        "Yarders",
        "Loaders",
        "Mobile mills",
        "More forestry equipment",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Hospitality",
      title: "Hospitality Equipment",
      subtitle: "Everything you need for your new restaurant.",
      image: {
        src: images.equipment.hospitalityIndustry,
        alt: "Hospitality",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Restaurant equipment",
        "Kitchen equipment",
        "Exhaust hood fan system",
        "Freezers",
        "Walk-in cooler/freezer",
        "Ovens",
        "Display cases",
        "Restaurant furniture",
        "Liquor systems",
        "POS systems",
        "Audio/video systems",
        "Draft beer systems",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Fitness",
      title: "Fitness Equipment",
      subtitle: "Leasing gym equipment has never been easier.",
      image: {
        src: images.equipment.gymIndustry,
        alt: "Fitness",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Gym equipment",
        "Treadmills",
        "Cardio equipment",
        "Bikes",
        "Ellipticals",
        "Barbells and dumbbells",
        "TVs",
        "Flooring",
        "Rubber floor mats",
        "More fitness equipment",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Health and Wellness",
      title: "Health and Wellness Equipment",
      subtitle: "We also lease health and wellness equipment.",
      image: {
        src: images.equipment.healthIndustry,
        alt: "Health and Wellness",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "POS systems",
        "Health equipment",
        "Float beds",
        "Tanning beds",
        "Laser machines",
        "Infrared saunas",
        "Tattoo removal equipment",
        "Dental equipment",
        "Cabinetry",
        "And more",
      ],
    },
    {
      menuItem: "altTitle",
      altTitle: "Manufacturing",
      title: "Manufacturing Equipment",
      subtitle: "Want manufacturing equipment? We can help with that.",
      image: {
        src: images.equipment.manufacturingIndustry,
        alt: "Manufacturing",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
      content: [
        "Presses",
        "Woodworking equipment",
        "Edge banders",
        "Packaging machines",
        "Laser cutting machines",
        "CNC machines",
        "Polution control equipment",
        "3D printers",
        "Control systems",
        "Dispensers",
        "Storage equipment",
        "And more",
      ],
    },
    {
      title: "Anything else?",
      subtitle:
        "We lease so much more, so contact us and we will get you sorted.",
      image: {
        src: images.equipment.anythingElse,
        alt: "Anything else?",
      },
      button: <OpenContactModalButton>Get started</OpenContactModalButton>,
    },
  ],
}

export default iwsContent
